# Generated by Django 4.2.3 on 2023-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='add', max_length=50),
        ),
    ]
