# Generated by Django 4.2.3 on 2023-07-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_domain_admin',
            field=models.BooleanField(default=False),
        ),
    ]
