# Generated by Django 4.2.3 on 2023-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_is_domain_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_domain_admin',
            field=models.BooleanField(default=False),
        ),
    ]
