# Generated by Django 4.2.3 on 2023-07-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_domain_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_domain_admin',
        ),
    ]
